/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:3ade2953-d737-4184-a391-eb810a8241ca",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_tGFMRzjck",
    "aws_user_pools_web_client_id": "4n0goubgg6j9dj94kgtdokpn30",
    "oauth": {},
    "aws_mobile_analytics_app_id": "4aeeeb29d2804e838de4d3b6b4b8c02c",
    "aws_mobile_analytics_app_region": "eu-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "CYSAPI",
            "endpoint": "https://tbxardm63f.execute-api.eu-west-1.amazonaws.com/staging",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
